version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: october-api:dev
    container_name: october-api
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: october-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - redis-data:/data
    networks:
      - appnet

  worker:
    build:
      context: ./worker
    image: october-worker:dev
    container_name: october-worker
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
    networks:
      - appnet

networks:
  appnet:

volumes:
  redis-data:
