alertmanager:
  enabled: true
  config:
    global:
      slack_api_url_file: /etc/alertmanager/secrets/am-slack-webhook/webhook
    route:
      receiver: default
      group_by: [namespace, alertname]
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 2h
      routes:
        - matchers: ['namespace="october"']
          receiver: default
    receivers:
      - name: default
        slack_configs:
          - channel: "#devops-alerts"
            send_resolved: true
            title: '{{ .CommonLabels.alertname }} ({{ .Status | toUpper }})'
            text: |-
              Alert:  {{ .CommonLabels.alertname }}
              Status: {{ .Status }}
              Namespace: {{ .CommonLabels.namespace }}
              Labels:
              {{- range $k, $v := .CommonLabels }}
                - {{$k}}={{$v}}
              {{- end }}
  alertmanagerSpec:
    secrets:
      - am-slack-webhook
