apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: {{ .Values.namespace }}
  labels: { app: worker }
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels: { app: worker }
  template:
    metadata:
      labels: { app: worker }
    spec:
      terminationGracePeriodSeconds: 20
      securityContext:
        runAsNonRoot: true
        runAsUser: 10002
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef: { name: app-config }
            {{- if .Values.secrets }}
            - secretRef: { name: app-secret }
            {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
