
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: {{ .Values.namespace }}
  labels:
    app: worker
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: worker
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ default (include "app.fullname" .) .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 20
      {{- with (.Values.worker.podSecurityContext | default .Values.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.worker.nodeSelector | default .Values.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.worker.tolerations | default .Values.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.worker.affinity | default .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClass.enabled }}
      priorityClassName: {{ .Values.priorityClass.name }}
      {{- end }}
      {{- if .Values.tmpVolume.enabled }}
      volumes:
        - name: tmp
          emptyDir:
            {{- if .Values.tmpVolume.medium }}
            medium: {{ .Values.tmpVolume.medium }}
            {{- end }}
            {{- if .Values.tmpVolume.sizeLimit }}
            sizeLimit: {{ .Values.tmpVolume.sizeLimit }}
            {{- end }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef: { name: app-config }
            {{- if .Values.secrets }}
            - secretRef: { name: app-secret }
            {{- end }}
          {{- with (.Values.worker.containerSecurityContext | default .Values.containerSecurityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.tmpVolume.enabled }}
          volumeMounts:
            - name: tmp
              mountPath: {{ .Values.tmpVolume.mountPath }}
          {{- end }}
        {{- if .Values.worker.celeryExporter.enabled }}
        - name: celery-exporter
          image: {{ .Values.worker.celeryExporter.image }}
          ports:
            - name: metrics
              containerPort: 9808
          args:
            - --broker-url=redis://redis:6379/0
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
        {{- end }}

