{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .Values.api.ingress.className }}
  rules:
    - host: {{ required "Set .api.ingress.host" .Values.api.ingress.host }}
      http:
        paths:
          - path: {{ .Values.api.ingress.path | default "/(.*)" }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: {{ .Values.api.service.port }}
{{- end }}
