{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.allowApiToRedis }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-allow-egress-redis
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: api
  policyTypes: ["Egress"]
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: redis
      ports:
        - protocol: TCP
          port: 6379
{{- end }}
