{{- if .Values.pdb.worker.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.pdb.worker.minAvailable }}
  selector:
    matchLabels:
      app: worker
{{- end }}
