{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: "{{ $v }}"
  {{- end }}
{{- end }}
