apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    app: api
spec:
  type: {{ .Values.api.service.type }}
  selector: { app: api }
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
