{{- if and .Values.redis.enabled .Values.redis.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    release: mon
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: redis
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 5s
      path: /metrics
{{- end }}
